[application]
port = 8001
host = "127.0.0.1"

[database]
host = "127.0.0.1"
port = 5433
# host = "postgres"
# port = 5432
username = "postgres"
password = "password"
database_name = "newsletter"

[email_client]
base_url = "https://app.mailgun.com"
sender_email = "something@gmail.com"
